//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.ServiceReferenceJoueur {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JoueurClient", Namespace="http://schemas.datacontract.org/2004/07/Wazabi.Client")]
    [System.SerializableAttribute()]
    public partial class JoueurClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfirmPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MdpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PseudoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfirmPassword {
            get {
                return this.ConfirmPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmPasswordField, value) != true)) {
                    this.ConfirmPasswordField = value;
                    this.RaisePropertyChanged("ConfirmPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mdp {
            get {
                return this.MdpField;
            }
            set {
                if ((object.ReferenceEquals(this.MdpField, value) != true)) {
                    this.MdpField = value;
                    this.RaisePropertyChanged("Mdp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pseudo {
            get {
                return this.PseudoField;
            }
            set {
                if ((object.ReferenceEquals(this.PseudoField, value) != true)) {
                    this.PseudoField = value;
                    this.RaisePropertyChanged("Pseudo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceJoueur.IGestionJoueur")]
    public interface IGestionJoueur {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJoueur/Inscription", ReplyAction="http://tempuri.org/IGestionJoueur/InscriptionResponse")]
        bool Inscription(WebUI.ServiceReferenceJoueur.JoueurClient joueur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJoueur/Inscription", ReplyAction="http://tempuri.org/IGestionJoueur/InscriptionResponse")]
        System.Threading.Tasks.Task<bool> InscriptionAsync(WebUI.ServiceReferenceJoueur.JoueurClient joueur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJoueur/Connexion", ReplyAction="http://tempuri.org/IGestionJoueur/ConnexionResponse")]
        WebUI.ServiceReferenceJoueur.JoueurClient Connexion(WebUI.ServiceReferenceJoueur.JoueurClient joueur);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJoueur/Connexion", ReplyAction="http://tempuri.org/IGestionJoueur/ConnexionResponse")]
        System.Threading.Tasks.Task<WebUI.ServiceReferenceJoueur.JoueurClient> ConnexionAsync(WebUI.ServiceReferenceJoueur.JoueurClient joueur);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionJoueurChannel : WebUI.ServiceReferenceJoueur.IGestionJoueur, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionJoueurClient : System.ServiceModel.ClientBase<WebUI.ServiceReferenceJoueur.IGestionJoueur>, WebUI.ServiceReferenceJoueur.IGestionJoueur {
        
        public GestionJoueurClient() {
        }
        
        public GestionJoueurClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionJoueurClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionJoueurClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionJoueurClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Inscription(WebUI.ServiceReferenceJoueur.JoueurClient joueur) {
            return base.Channel.Inscription(joueur);
        }
        
        public System.Threading.Tasks.Task<bool> InscriptionAsync(WebUI.ServiceReferenceJoueur.JoueurClient joueur) {
            return base.Channel.InscriptionAsync(joueur);
        }
        
        public WebUI.ServiceReferenceJoueur.JoueurClient Connexion(WebUI.ServiceReferenceJoueur.JoueurClient joueur) {
            return base.Channel.Connexion(joueur);
        }
        
        public System.Threading.Tasks.Task<WebUI.ServiceReferenceJoueur.JoueurClient> ConnexionAsync(WebUI.ServiceReferenceJoueur.JoueurClient joueur) {
            return base.Channel.ConnexionAsync(joueur);
        }
    }
}
