//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wazabi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carte
    {
        public int Id { get; set; }
        public string CodeEffet { get; set; }
        public int Cout { get; set; }
        public string Description { get; set; }
        public string Effet { get; set; }
        public string ImageRef { get; set; }
    }
}
