//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wazabi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Joueur
    {
        public int Id { get; set; }
        public string Pseudo { get; set; }
        public byte[] MotDePasse { get; set; }
        public byte[] Sel { get; set; }
        public string IconeRef { get; set; }
    }
}
